### ISSUE TITLE
koa-bodyparser 报错 413 Payload Too Large  需增加配置项

### ISSUE THREAD

**Issue by mzyailqq** [qails/qails#5]
koa-bodyparser 对请求体大小做了限制
![image](https://user-images.githubusercontent.com/1835371/40224226-145ea14e-5ab8-11e8-9a9f-f3043d92e95b.png)
，当接口参数过大超出限制会提示413 Payload Too Large  ，需在qails中提供配置项供外部配置，如下测试ok
![image](https://user-images.githubusercontent.com/1835371/40224320-5c8f838e-5ab8-11e8-889b-1b1feba5a774.png)

**Comment by zhongzhi107** [comment]
多谢反馈。

在 qails@>=3.0.0 版本中已经支持 bodyParser 自定义参数，qail@2.x 中不支持。

针对qails@2.x，在 a666b45ae3da82a1e728cb9841fd8024e74ff44a 提交中修改了该问题，发布了 qails@2.3.3-fix.2

### 用法
在 `.env` 文件中增加 `JSON_LIMIT` 来控制
```
JSON_LIMIT=2mb
# FORM_LIMIT=56kb
```
